augmented compatibility with both linux and macOS
Nephylhim/gotoFonction pull request #4
Opened 2019-04-24 13:14 UTC by tvdu29

changed shell scrap method for better interoperability between Linux
and macOS
added macOS specific '-zsh' shell name

2019-04-25 11:03 UTC, Nephylhim requested changes
I do not fully understand your `awk` command but it seems to work.
I get a `/usr/bin/zsh` from it. But none of your condition pass for me (`elif [[ $used_shell == "zsh" ]];` and `elif [[ $used_shell == "-zsh" ]];`).

I agree with the awk proposition but disagree with conditions and code duplication.
I'd merge this when these problems are solved =)

2019-04-25 11:03 UTC, Nephylhim commented on gotoFct.sh
> +elif [[ $used_shell == "zsh" ]]; then
Mmmh, I saw someone else who got this kind of problem with bash too, he was using /bin/bash directly and so the shell wasn't properly detected.
I think changing the condition to an including string comparaison will be better :
`if [[ $used_shell == *"zsh"* ]]; then`
This way, you don't have to multiplicate the tests : zsh || /usr/bin/zsh || ...

2019-04-25 11:03 UTC, Nephylhim commented on gotoFct.sh
> +    my_dir="$(dirname "$0")"
Please do not duplicate code. You should add a statement in the condition instead.

2019-04-25 11:03 UTC, Nephylhim commented on gotoFct.sh
> +    autoload -U +X compinit && compinit
Same problem there. We do not need code duplication to make this work.

2019-04-25 17:56 UTC, tvdu29 commented
added pattern matching for shell names to remove code duplication.
tested on Bash and Zsh with absolute and relative paths both on Linux and macOS.

2019-04-26 07:39 UTC, Nephylhim approved these changes

2019-04-26 07:39 UTC, merged